print("Welcome to your adventure simulator. I am going to ask you a bunch of questions and then create an epic story with you as the star!")
print()
name = input("What is your name? ")
enemy = input("What is your worst enemy’s name? ")
superpower = input("What is your superpower? ")
live = input("Where do you live? ")
favFood = input("What is your favorite food? ")
print()
print("Hello", name, "Your ability to", superpower, "will make sure you never have to look at", enemy, "again." "Go eat", favFood, "as you walk down the streets of", live, "and use", superpower, "for good and not evil!")
print("Uh, oh, you've been given a", "\033[31m", "warning", "\033[0m", "for being a bad, bad person.")
